Replaced building locally section with documentation section
adafruit/Adafruit_CircuitPython_BusDevice pull request #34
Opened 2019-10-23 12:52 UTC by dherrada

@kattni

2019-10-23 19:17 UTC, kattni requested changes
@dherrada I'm not sure why you closed the other one to open this one. We still need the changes requested on the other one. It needs PyPI instructions, and it needs the Installation section removed. You can make the changes on this PR.

2019-10-24 13:57 UTC, dherrada commented
@kattni Sorry about that. I got confused and thought you were referring to removing the "installing from pypi" section instead of the "installation" section.

2019-10-24 16:28 UTC, kattni requested changes
Thanks for adding this! There are two whitespace issues, see inline comments. Get those fixed up and it's ready to merge.

2019-10-24 16:28 UTC, kattni commented on README.rst
> +.. code-block:: shell
There should be a blank line between this and the line above it.

2019-10-24 16:28 UTC, kattni commented on README.rst
> +.. code-block:: shell
There should be a blank line between this and the line above it.

2019-10-25 18:28 UTC, kattni approved these changes

2019-10-25 18:28 UTC, merged