Add timeouts to bus devices.
adafruit/Adafruit_CircuitPython_BusDevice pull request #51
Opened 2020-05-03 03:37 UTC by TG-Techie

I noticed that on some devices (so far only nrf52840s) after many reboots all hardware locking hangs. this modification adds timeouts to the bus devices (default of .25 seconds to be generous).  the timeout can be deactivated by passing `None` as the timeout. if the time runs out an exception of type `exception` is thrown.

this code is tested

2020-05-04 03:08 UTC, theacodes requested changes
Overall looks pretty good, just some small comments.

2020-05-04 03:08 UTC, theacodes commented on adafruit_bus_device/i2c_device.py
> +            lock_start_time = time.monotonic()
Suggestion: use `time.monotonic_ns()` throughout as it'll avoid issues with floating point precision when the program runs for a long time.

2020-05-04 03:08 UTC, theacodes commented on adafruit_bus_device/i2c_device.py
> +    def __init__(self, i2c, device_address, probe=True, timeout=0.25):
Can you add the `timeout` parameter to the docstring above here?

2020-05-04 03:08 UTC, theacodes commented on adafruit_bus_device/i2c_device.py
> +                    raise Exception("'I2CDevice' lock timed out")
Don't raise bare `Exception`s. It seems other Adafruit libraries use `RuntimeError` here. [source](https://github.com/adafruit/Adafruit_CircuitPython_ESP32SPI/blob/master/adafruit_esp32spi/adafruit_esp32spi.py#L205).

2020-06-07 02:31 UTC, dhalbert requested changes
I am not sure what problem this is trying to solve. If you are seeing hangs on I2C devices, we have an issue open to solve that problem at a lower level. See https://github.com/adafruit/circuitpython/issues/2253. I have plans to fix this at some point.

2020-06-07 02:31 UTC, dhalbert commented on adafruit_bus_device/i2c_device.py
> +    def __init__(self, i2c, device_address, probe=True, timeout=250):
Please go back to floating point seconds. We are trying to be uniform and always use float seconds.

2020-06-07 03:15 UTC, dhalbert commented
The I2C bus hangs mentioned in that cannot be solved with timeouts in Python; timeouts have to be added in the C code at a low level where the bus status is checked.

2020-08-17 19:26 UTC, kattni commented
This issue needs to be fixed in the CircuitPython core, not the bus_device library. I'm closing this in favor of https://github.com/adafruit/circuitpython/issues/2253

2020-08-17 19:26 UTC, closed without merging